version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-web:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email your-email@example.com
      --agree-tos --no-eff-email
      -d hamza-qureshi.duckdns.org

volumes:
  certbot-etc:
  certbot-web:

