version: "3.9"

services:
  api:
    build: .
    container_name: portfolio-api
    expose:
      - "8000"
    restart: always
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge
